---
  image: base/archlinux:latest

  build-repo:
    stage: build
    artifacts:
      expire_in: 1d
      paths:
        - repo
    before_script:
      - pacman -Syy
      - pacman -Syu --noconfirm
      - pacman -S git base-devel --noconfirm
      - curl -sS "https://gitlab.com/arch-dual-boot/arch-x-os/raw/master/scripts/pacman.conf.patch" | patch -p1 /etc/pacman.conf
      - pacman -Syy
      - pacman -Syu --noconfirm
      - "echo 'nobody ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
    script:
      - mkdir repo
      - mkdir repo/x86_64
      - for d in *; do [ -f "${d}/PKGBUILD" ] && (cd $(readlink -f "${d}") && sudo -u nobody BUILDDIR=/tmp/makepkg PKGDEST=repo/x86_64 SRCDEST=/tmp/src SRCPKGDEST=/tmp/srcpackages LOGDEST=/tmp/makepkglogs makepkg -cs --noconfirm); done
      - repo-add repo/x86_64/arcus.db.tar.gz repo/x86_64/*.pkg.tar.xz

  pages:
    stage: deploy
    dependencies:
      - build-repo
    only:
      - master
    artifacts:
      paths:
        - public
    script:
      - mkdir .public
      - cp -r repo .public
      - mv .public public

  stages:
    - build
    - deploy
